trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  bkstrgrg: 'rg-sanhorva'
  bkstrg: 'sasanhorva'
  bkcontainer: 'tfstate'
  bkstrgkey: 'terraform.tfstate'
  
stages:
  - stage: tfdestroy
    jobs:
      - job: destroy
        steps:
        - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@1
          displayName: tfinstall
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          displayName: 'init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'ZEISSgroup-DI05-ASM-Learning'
            backendAzureRmResourceGroupName: '$(bkstrgrg)'
            backendAzureRmStorageAccountName: '$(bkstrg)'
            backendAzureRmContainerName: '$(bkcontainer)'
            backendAzureRmKey: '$(bkstrgkey)'

        - task: TerraformTaskV4@4
          displayName: plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'ZEISSgroup-DI05-ASM-Learning'

        - task: TerraformTaskV4@4
          displayName: destroy
          inputs:
            provider: 'azurerm'
            command: 'destroy'
            environmentServiceNameAzureRM: 'ZEISSgroup-DI05-ASM-Learning'
